name: Build and Deploy Templates
run-name: ${{ github.actor }} deploing templates
on: [push]

jobs:
  build_templates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - run: npm install
      # Runs "build": "email export --outDir ./public"
      - run: npm run build --if-present

      - name: Add & Commit Built files
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: public/
          author_name: github_actions

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: templates
          path: public/

  deploy_templates:
    runs-on: ubuntu-latest
    needs: build_templates

    steps:
      #  Checkout the code to be built
      - name: Check out code
        uses: actions/checkout@v4

      # Download Artifact
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: templates
          path: public/
      - name: Test artifact Download
        run: ls -R

      - name: Use custom action to deploy templates
        uses: ./.github/actions/deploy-templates-action/
